export const portugueseWords = [
  'Acessar',
  'Rede',
  'Erro',
  'Função',
  'Lista',
  'Objeto',
  'Variável',
  'Texto',
  'Número',
  'Verdadeiro/Falso',
  'Propriedade',
  'Pasta',
  'Buscar',
  'Não definido',
  'Arquivo',
  'Configurações',
  'Rodar',
  'Área de Trabalho',
  'Buscar',
  'Inesperado',
  'Inválido',
  'Não Encontrado',
  'Permissão Negada',
  'Conexão Recusada',
  'Não Capturado',
]
